INSERT INTO public.users(id, FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, ID_CUSTOMER_CREATED_BY, ID_CUSTOMER_UPDATE_BY, CREATE_DATE, UPDATE_DATE)
VALUES (1000,'test1','test1','test1','test1@gmail.com','1231234',null,null,null,null);

INSERT INTO public.users(id, FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PASSWORD, ID_CUSTOMER_CREATED_BY, ID_CUSTOMER_UPDATE_BY, CREATE_DATE, UPDATE_DATE)
VALUES (1001,'test2','test2','test2','test2@gmail.com','1231234',null,null,null,null);

INSERT INTO public.users(id,FIRST_NAME,LAST_NAME,USERNAME,EMAIL,PASSWORD,ID_CUSTOMER_CREATED_BY, ID_CUSTOMER_UPDATE_BY, CREATE_DATE, UPDATE_DATE)
VALUES (1002,'test3','test3','test3','test3@gmail.com','1231234',null,null,null,null);

INSERT INTO public.users(id,FIRST_NAME,LAST_NAME,USERNAME,EMAIL,PASSWORD,ID_CUSTOMER_CREATED_BY, ID_CUSTOMER_UPDATE_BY, CREATE_DATE, UPDATE_DATE)
VALUES (1003,'test4','test4','test4','test4@gmail.com','1231234',null,null,null,null);

INSERT INTO public.users(id,FIRST_NAME,LAST_NAME,USERNAME,EMAIL,PASSWORD,ID_CUSTOMER_CREATED_BY, ID_CUSTOMER_UPDATE_BY, CREATE_DATE, UPDATE_DATE)
VALUES (1004,'berkay','gülen','berkay123','berkay@gmail.com','$2a$10$4seuOSqfOERAPVpJrlVEGO/5H2RaP9REnnzGzQwy593vPsgkMBqXS',null,null,null,null);

